//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ECModel : DbContext
    {
        public ECModel()
            : base("name=ECModel")
        {
        }

          public ECModel(string connString)
            : base(connString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MastProduct> MastProducts { get; set; }
        public virtual DbSet<ProdDiscount> ProdDiscounts { get; set; }
        public virtual DbSet<ProdPricing> ProdPricings { get; set; }
    }
}
