//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdPricing
    {
        public int ProdPriceID { get; set; }
        public int ProdID { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public bool PromoOffer { get; set; }
    
        public virtual MastProduct MastProduct { get; set; }
    }
}
