//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdDiscount
    {
        public int DiscID { get; set; }
        public int ProdID { get; set; }
        public string DiscType { get; set; }
        public Nullable<decimal> DiscUnit { get; set; }
        public Nullable<int> MinOrderQty { get; set; }
        public int DiscPriority { get; set; }
        public string DiscDesc { get; set; }
        public Nullable<decimal> FixedPrice { get; set; }
        public Nullable<int> ChargeForQty { get; set; }
        public Nullable<decimal> DiscPercent { get; set; }
    
        public virtual MastProduct MastProduct { get; set; }
    }
}
